import {
  User,
  Organization,
  Opportunity,
  Course,
  Donation,
  Achievement,
  PointTransaction,
  LeaderboardUser,
  Application,
  Certificate,
  Notification,
} from './types';

// Initial Mock Volunteer
export const initialMockUser: User = {
  id: 'user-001',
  firstName: 'محمد',
  lastName: 'أحمد',
  email: 'mohamed@example.com',
  role: 'volunteer',
  wilaya: 'الجزائر',
  commune: 'الجزائر الوسطى',
  points: 350,
  volunteerHours: 42,
  completedOpportunities: 12,
  certificatesCount: 8,
  level: 'متطوع نشط',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  bio: 'شاب جزائري شغوف بالعمل التطوعي، حماية البيئة وتطوير المهارات الرقمية للشباب.',
  phone: '0550 12 34 56',
  birthDate: '1998-05-14',
  educationLevel: 'ماستر',
  specialty: 'إعلام آلي وهندسة برمجيات',
  skills: ['تنظيم الفعاليات', 'التواصل', 'العمل الجماعي', 'الإسعافات الأولية', 'التصميم الرقمي'],
};

// Initial Mock Organization (Jam'iyat Al-Amal)
export const initialMockOrg: Organization = {
  id: 'org-001',
  name: 'جمعية الأمل لرعاية الشباب والبيئة',
  type: 'جمعية وطنية ذات طابع اجتماعي وبيئي',
  wilaya: 'بجاية',
  commune: 'بجاية',
  address: 'نهج أول نوفمبر، وسط المدينة، بجاية',
  verified: true,
  opportunitiesCount: 12,
  volunteersCount: 57,
  hoursCount: 340,
  email: 'contact@association-alamal.dz',
  phone: '034 11 22 33',
  registrationNumber: 'DZ-BG-2018-0442',
  description:
    'جمعية شبابية رائدة تأسست بهدف تفعيل دور الشباب الجزائري في حماية البيئة والتضامن الاجتماعي والتعليم.',
  logo: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=200',
  coverImage:
    'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&q=80&w=1200',
  foundedYear: '2018',
  website: 'https://association-alamal.dz',
};

// Other registered organizations
export const initialOrganizations: Organization[] = [
  initialMockOrg,
  {
    id: 'org-002',
    name: 'الهلال الأحمر الجزائري - لجنة البليدة',
    type: 'منظمة إنسانية وطنية',
    wilaya: 'البليدة',
    commune: 'البليدة',
    address: 'شارع الشهداء، البليدة',
    verified: true,
    opportunitiesCount: 24,
    volunteersCount: 190,
    hoursCount: 1250,
    email: 'blida@cra-dz.org',
    phone: '025 39 40 41',
    registrationNumber: 'CRA-BL-09',
    description: 'الفرع المحلي للهلال الأحمر الجزائري المعني بتقديم الإغاثة والمساعدات والتكوين الإسعافي.',
    logo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=200',
    coverImage: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=1200',
    foundedYear: '1962',
  },
  {
    id: 'org-003',
    name: 'جمعية صناع الأثر وهران',
    type: 'جمعية ولائية تضامنية',
    wilaya: 'وهران',
    commune: 'وهران',
    address: 'حي كاستور، وهران',
    verified: true,
    opportunitiesCount: 8,
    volunteersCount: 82,
    hoursCount: 420,
    email: 'oran.impact@gmail.com',
    phone: '041 55 66 77',
    registrationNumber: 'DZ-OR-2021-118',
    description: 'مبادرات إنسانية وتضامنية موجهة لمساعدة الأسر المحتاجة والأطفال الأيتام في الغرب الجزائري.',
    logo: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&q=80&w=200',
    coverImage: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&q=80&w=1200',
    foundedYear: '2021',
  },
  {
    id: 'org-004',
    name: 'نادي تكنولوجيا المستقبل للشباب',
    type: 'نادي علمي وتكنولوجي',
    wilaya: 'الجزائر',
    commune: 'باب الزوار',
    address: 'جامعة العلوم والتكنولوجيا هواري بومدين، باب الزوار',
    verified: true,
    opportunitiesCount: 6,
    volunteersCount: 45,
    hoursCount: 280,
    email: 'futuretech.usthb@gmail.com',
    phone: '021 24 79 12',
    registrationNumber: 'CLUB-USTHB-2022',
    description: 'نادي جامعي يهدف إلى نشر الثقافة الرقمية والبرمجة والذكاء الاصطناعي بين الأطفال والشباب.',
    logo: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=200',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1200',
    foundedYear: '2022',
  },
];

// Volunteer Opportunities
export const initialOpportunities: Opportunity[] = [
  {
    id: 'opp-001',
    title: 'تنظيف الشواطئ وحماية الساحل في بجاية',
    description: 'مبادرة بيئية كبرى لتنظيف الشواطئ الصخرية والرملية وإعادة فرز النفايات البلاستيكية في خليج بجاية.',
    detailedDescription:
      'تنظم جمعية الأمل بالتنسيق مع مديرية البيئة يوماً تطوعياً بيئياً لتنظيف الشواطئ من النفايات البلاستيكية وتوعية المصطافين والزوار بأهمية الحفاظ على النظم البحرية. سيتلقى كل متطوع عتاد التنظيف، شهادة مشاركة ونقاط تطوع معتمدة.',
    organizationId: 'org-001',
    organizationName: 'جمعية الأمل لرعاية الشباب والبيئة',
    organizationLogo: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=200',
    category: 'البيئة',
    wilaya: 'بجاية',
    commune: 'بجاية',
    duration: 'يوم واحد',
    type: 'حضوري',
    points: 50,
    volunteersNeeded: 20,
    volunteersRegistered: 13,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-09-25',
    endDate: '2026-09-25',
    requirements: ['العمر أكبر من 16 سنة', 'ارتداء ملابس وأحذية مريحة', 'روح العمل الجماعي'],
    benefits: ['50 نقطة تطوعية معتمدة', 'شهادة مشاركة رقمية', 'وجبة خفيفة ومشروبات', 'تأمين ضد الحوادث'],
    duties: ['جمع وفرز النفايات في أكياس مخصصة', 'توزيع مطويات توعوية على الزوار', 'المساعدة في تحميل النفايات'],
    urgent: false,
    featured: true,
  },
  {
    id: 'opp-002',
    title: 'حملة تشجير غابات الأطلس البليدي',
    description: 'غرس 1000 شجرة صنوبر وأرز أطلسي لإعادة تأهيل المساحات الغابية المتضررة بجبال الشريعة.',
    detailedDescription:
      'ضمن المبادرة الوطنية للتشجير، يدعوكم الهلال الأحمر الجزائري للمشاركة في يوم غرس الأشجار في الحظيرة الوطنية للشريعة. نهدف إلى غرس 1000 شجيرة بمشاركة الشباب والعائلات.',
    organizationId: 'org-002',
    organizationName: 'الهلال الأحمر الجزائري - لجنة البليدة',
    organizationLogo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=200',
    category: 'البيئة',
    wilaya: 'البليدة',
    commune: 'الشريعة',
    duration: 'يوم واحد',
    type: 'حضوري',
    points: 70,
    volunteersNeeded: 35,
    volunteersRegistered: 28,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-10-02',
    endDate: '2026-10-02',
    requirements: ['اللياقة البدنية للمشي الجبلي', 'إحضار قبعة وماء', 'الالتزام بتوجيهات المرشدين الغابيين'],
    benefits: ['70 نقطة تطوعية', 'نقل مجاني من محطة البليدة', 'شهادة تقدير من إدارة الغابات', 'غداء جبلي تقليدي'],
    duties: ['حفر الجذور وغرس الشتلات', 'سقي الشجيرات المزروعة', 'تثبيت الأوتاد الداعمة'],
    urgent: true,
    featured: true,
  },
  {
    id: 'opp-003',
    title: 'دروس دعم وتقوية مجانية لتلاميذ الابتدائي',
    description: 'تأطير حصص مراجعة في الرياضيات واللغات لأبناء العائلات ذات الدخل المحدود قبيل الامتحانات.',
    detailedDescription:
      'مبادرة تربوية تضامنية تهدف إلى مرافقة التلاميذ المعوزين في الطور الابتدائي لتمكينهم من استدراك النقائص الدراسية في مادتي الرياضيات واللغة العربية.',
    organizationId: 'org-001',
    organizationName: 'جمعية الأمل لرعاية الشباب والبيئة',
    organizationLogo: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=200',
    category: 'التعليم',
    wilaya: 'الجزائر',
    commune: 'الجزائر الوسطى',
    duration: 'أسبوع',
    type: 'حضوري',
    points: 80,
    volunteersNeeded: 15,
    volunteersRegistered: 9,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-10-05',
    endDate: '2026-10-12',
    requirements: ['مستوى جامعي (ليسانس أو ماستر)', 'الصبر والقدرة البيداغوجية على تبسيط المفاهيم للأطفال'],
    benefits: ['80 نقطة تطوعية', 'شهادة تأطير بيداغوجي', 'توفير المقر والوسائل التعليمية'],
    duties: ['تقديم تمارين تطبيقية للأطفال', 'مساعدة التلاميذ في الواجبات المنزلية', 'إعداد تقرير تقييمي بسيط'],
    urgent: false,
    featured: true,
  },
  {
    id: 'opp-004',
    title: 'توزيع قفف ومساعدات شتوية على القرى النائية',
    description: 'تعبئة وتوزيع الطرود الغذائية والأغطية الشتوية على العائلات المعوزة في مناطق الظل بولاية الجلفة.',
    detailedDescription:
      'مع اقتراب فصل الشتاء، تنظم جمعية صناع الأثر حملة إغاثية لتوزيع طرود المواد الأساسية والأغطية الثقيلة للأسر في المناطق الجبلية والنائية.',
    organizationId: 'org-003',
    organizationName: 'جمعية صناع الأثر وهران',
    organizationLogo: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&q=80&w=200',
    category: 'التضامن',
    wilaya: 'الجلفة',
    commune: 'عين وسارة',
    duration: '2 - 3 أيام',
    type: 'حضوري',
    points: 60,
    volunteersNeeded: 25,
    volunteersRegistered: 19,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-10-15',
    endDate: '2026-10-17',
    requirements: ['الاستعداد للسفر الميداني', 'القدرة على ترتيب وحمل الطرود'],
    benefits: ['60 نقطة تطوعية', 'إقامة وإطعام موفر للمتطوعين', 'شهادة شكر وتقدير'],
    duties: ['تغليف وتصنيف المواد الغذائية', 'تحميل وتفريغ الشاحنات', 'توزيع القفف في القرى المستهدفة'],
    urgent: true,
    featured: false,
  },
  {
    id: 'opp-005',
    title: 'ورشات البرمجة والذكاء الاصطناعي للشباب (عن بعد)',
    description: 'تأطير وتدريب تلاميذ الثانوي على أساسيات لغة بايثون وتطوير تطبيقات الويب البسيطة.',
    detailedDescription:
      'نبحث عن متطوعين من طلبة ومهندسي الإعلام الآلي لتقديم حصص توجيهية عن بعد عبر Zoom لتلاميذ المدارس الراغبين في دخول عالم البرمجة والابتكار الرقمي.',
    organizationId: 'org-004',
    organizationName: 'نادي تكنولوجيا المستقبل للشباب',
    organizationLogo: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=200',
    category: 'التكنولوجيا',
    wilaya: 'وهران',
    commune: 'وهران',
    duration: 'أكثر من أسبوع',
    type: 'عن بعد',
    points: 90,
    volunteersNeeded: 10,
    volunteersRegistered: 7,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-10-01',
    endDate: '2026-10-25',
    requirements: ['إتقان أساسيات Python أو Web', 'اتصال إنترنت مستقر', 'ساعتان أسبوعياً للتأطير'],
    benefits: ['90 نقطة تطوعية', 'شهادة مدرب معتمدة من النادي العلمي', 'إمكانية إدارة مشاريع تقنية مستقبلية'],
    duties: ['شرح المفاهيم البرمجية الأساسية', 'تصحيح الأخطاء في مشاريع الطلبة', 'التحفيز وبث الشغف الرقمي'],
    urgent: false,
    featured: true,
  },
  {
    id: 'opp-006',
    title: 'تأطير الماراثون الرياضي الوطني للشباب في عنابة',
    description: 'المشاركة في تنظيم مسار الماراثون، استقبال العدائين، وتوزيع المياه والميداليات على خط النهاية.',
    detailedDescription:
      'فعالية رياضية سنوية تجمع مئات الرياضيين والهواة عبر كورنيش عنابة الساحر. يحتاج التنظيم إلى متطوعين نشطين لضمان سلامة المسار وتوجيه المشاركين.',
    organizationId: 'org-001',
    organizationName: 'جمعية الأمل لرعاية الشباب والبيئة',
    organizationLogo: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=200',
    category: 'الرياضة',
    wilaya: 'عنابة',
    commune: 'عنابة',
    duration: 'يوم واحد',
    type: 'حضوري',
    points: 40,
    volunteersNeeded: 40,
    volunteersRegistered: 32,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-10-20',
    endDate: '2026-10-20',
    requirements: ['النشاط والحيوية', 'الحضور في السادسة صباحاً', 'التفاعل الإيجابي مع الجمهور'],
    benefits: ['40 نقطة تطوعية', 'قميص وقبعة الفعالية الرسمية', 'وجبة إفطار وغداء', 'شهادة مشاركة'],
    duties: ['توزيع المياه عند نقاط التزود', 'توجيه العدائين في المنعطفات', 'تسليم الميداليات عند خط الوصول'],
    urgent: false,
    featured: false,
  },
  {
    id: 'opp-007',
    title: 'حملة التبرع بالدم ودعم مصالح الاستعجالات الطبية',
    description: 'مرافقة الفرق الطبية في توجيه المتبرعين، ملء الاستمارات وتقديم الإرشادات في قسنطينة.',
    detailedDescription:
      'تنظم المستشفيات الجامعية بقسنطينة بالتعاون مع الهلال الأحمر يوماً مفتوحاً للتبرع بالدم لسد العجز في بنوك الدم. دور المتطوع هو تنظيم الدور وتوعية المواطنين.',
    organizationId: 'org-002',
    organizationName: 'الهلال الأحمر الجزائري - لجنة البليدة',
    organizationLogo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=200',
    category: 'الصحة',
    wilaya: 'قسنطينة',
    commune: 'قسنطينة',
    duration: 'يوم واحد',
    type: 'حضوري',
    points: 50,
    volunteersNeeded: 30,
    volunteersRegistered: 21,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-10-28',
    endDate: '2026-10-28',
    requirements: ['اللباقة والهدوء', 'احترام البروتوكولات الصحية الوقائية'],
    benefits: ['50 نقطة تطوعية', 'فحص دم مجاني شامل للمتطوع', 'شهادة شكر إنسانية'],
    duties: ['استقبال المواطنين وتسجيل البيانات', 'مساعدة المتبرعين بالاسترخاء والعصائر', 'توزيع شهادات التبرع'],
    urgent: true,
    featured: false,
  },
  {
    id: 'opp-008',
    title: 'تزيين وترميم مكتبة بلدية للأطفال في تيزي وزو',
    description: 'رسم جداريات ملهمة وفهرسة الكتب لتجهيز فضاء مطالعة ممتع لأطفال قرية جبلية.',
    detailedDescription:
      'تهدف هذه الورشة التطوعية الفنية إلى إعادة تهيئة مكتبة القرية من خلال طلاء الجدران بألوان مبهجة ورسومات كرتونية وفهرسة 500 كتاب وقصة للأطفال.',
    organizationId: 'org-001',
    organizationName: 'جمعية الأمل لرعاية الشباب والبيئة',
    organizationLogo: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=200',
    category: 'الثقافة',
    wilaya: 'تيزي وزو',
    commune: 'أزفون',
    duration: '2 - 3 أيام',
    type: 'حضوري',
    points: 65,
    volunteersNeeded: 12,
    volunteersRegistered: 10,
    status: 'open',
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=800',
    startDate: '2026-11-04',
    endDate: '2026-11-06',
    requirements: ['مهارة في الرسم أو الخط العربي أو حب الكتب', 'روح المبادرة والإبداع'],
    benefits: ['65 نقطة تطوعية', 'تغطية مصاريف الإقامة والإطعام', 'معرض للصور المنجزة وتكريم'],
    duties: ['تلوين الجداريات وتصميم ركن القراءة', 'ترتيب وفهرسة القصص والكتب', 'تنظيم حفل افتتاح للأطفال'],
    urgent: false,
    featured: true,
  },
];

// Online Courses
export const initialCourses: Course[] = [
  {
    id: 'course-001',
    title: 'أساسيات العمل التطوعي وصناعة الأثر الإيجابي',
    subtitle: 'دورة تمهيدية شاملة لكل شاب يرغب في خوض غمار التطوع بفعالية واحترافية.',
    description:
      'تعلم المفاهيم الجوهرية للعمل التطوعي، حقوق وواجبات المتطوع، كيفية الاندماج في فرق العمل، وأسرار صناعة أثر ملموس ومستدام في محيطك ومجتمعك.',
    category: 'العمل الجمعوي',
    rating: 4.8,
    learnersCount: 1240,
    duration: 'ساعتان و 30 دقيقة',
    lessonsCount: 6,
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=800',
    instructor: {
      name: 'د. كريم بن سالم',
      role: 'خبير إدارة المنظمات غير الربحية والتنمية المجتمعية',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    },
    outcomes: [
      'فهم القيمة الأخلاقية والمجتمعية للتطوع',
      'معرفة الحقوق القانونية للمتطوع ومسؤولياته',
      'اكتساب مهارات الاندماج السريع والعمل ضمن فريق متنوع',
      'كيفية قياس وتقييم نتائج المبادرات المجتمعية',
    ],
    certificatePriceDzd: 1500,
    certificatePricePoints: 100,
    featured: true,
    lessons: [
      {
        id: 'les-101',
        title: '01 - مدخل إلى مفهوم العمل التطوعي وأبعاده في الجزائر',
        duration: '18 دقيقة',
        order: 1,
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        summary: 'استعراض تاريخي ومفهومي للتطوع والتضامن في المجتمع الجزائري والتحديات الحالية.',
      },
      {
        id: 'les-102',
        title: '02 - ميثاق المتطوع: الحقوق، الواجبات والمسؤوليات الأخلاقية',
        duration: '22 دقيقة',
        order: 2,
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        summary: 'كيف تلتزم بمواعيدك وتحافظ على سلامتك ومصداقية الجمعية التي تمثلها.',
      },
      {
        id: 'les-103',
        title: '03 - العمل الجماعي وحل النزاعات الميدانية',
        duration: '25 دقيقة',
        order: 3,
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        summary: 'استراتيجيات التواصل الفعّال بين المتطوعين وتجاوز ضغط الميدان بحكمة.',
      },
      {
        id: 'les-104',
        title: '04 - التواصل الإيجابي مع المستفيدين والجمهور',
        duration: '24 دقيقة',
        order: 4,
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        summary: 'أساليب التعامل الإنساني مع الفئات الهشة، الأسر المعوزة، والأطفال.',
      },
      {
        id: 'les-105',
        title: '05 - إدارة المبادرات الصغيرة وتوثيق النجاح',
        duration: '30 دقيقة',
        order: 5,
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        summary: 'كيفية التخطيط لنشاط ميداني في 5 خطوات وتوثيق الأثر بالصور والأرقام.',
      },
      {
        id: 'les-106',
        title: '06 - الاختبار النهائي وخطة العمل الشخصية',
        duration: '20 دقيقة',
        order: 6,
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
        summary: 'اختبار تقييمي لاكتساب الشهادة وتحديد مجالات التطوع المناسبة لشغفك.',
      },
    ],
  },
  {
    id: 'course-002',
    title: 'الإسعافات الأولية والتعامل مع الطوارئ والحوادث',
    subtitle: 'تعلم تقنيات إنقاذ الحياة الأساسية لتكون مسعفاً مستعداً في الميدان والمنزل.',
    description:
      'دورة تطبيقية عملية تغطي التصرف الصحيح عند الإغماء، الجروح، الكسور، الحروق، والإنعاش القلبي الرئوي حتى وصول الإسعاف المتخصص.',
    category: 'الإسعافات الأولية',
    rating: 4.9,
    learnersCount: 2150,
    duration: '3 ساعات و 45 دقيقة',
    lessonsCount: 8,
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=800',
    instructor: {
      name: 'د. أمينة زروقي',
      role: 'طبيبة استعجالية ومدربة إسعافات معتمدة',
      avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
    },
    outcomes: [
      'إتقان خطوات سلسلة النجاة والإنعاش القلبي',
      'إيقاف النزيف وتضميد الجروح بسلامة',
      'التعامل الآمن مع حالات الاختناق لدى الكبار والأطفال',
      'تجنب الأخطاء الشائعة والخطيرة في الإسعاف',
    ],
    certificatePriceDzd: 1500,
    certificatePricePoints: 100,
    featured: true,
    lessons: [
      { id: 'les-201', title: '01 - مبادئ السلامة وحماية النفس أولاً', duration: '20 دقيقة', order: 1, summary: 'تقييم مكان الحادث وتأمين النفس قبل التدخل الإسعافي.' },
      { id: 'les-202', title: '02 - فحص الوعي ومجرى التنفس', duration: '25 دقيقة', order: 2, summary: 'وضعية الإفاقة الجانبية ومتى نستخدمها.' },
      { id: 'les-203', title: '03 - الإنعاش القلبي الرئوي (CPR)', duration: '35 دقيقة', order: 3, summary: 'الضغطات الصدرية الصحيحة واستخدام جهاز مزيل الرجفان.' },
      { id: 'les-204', title: '04 - التعامل مع الغصة والاختناق', duration: '20 دقيقة', order: 4, summary: 'مناورة هيمليك للكبار والأطفال الرضع.' },
      { id: 'les-205', title: '05 - النزيف الحاد والصدمة', duration: '30 دقيقة', order: 5, summary: 'تقنيات الضغط المباشر والعصابة الضاغطة.' },
      { id: 'les-206', title: '06 - الحروق واللسعات', duration: '25 دقيقة', order: 6, summary: 'درجات الحروق والمياه الجارية وتجنب الوصفات المنزلية الضارة.' },
      { id: 'les-207', title: '07 - الكسور والالتواءات', duration: '30 دقيقة', order: 7, summary: 'تثبيت الأطراف المصابة وتفادي تحريك المصاب بعشوائية.' },
      { id: 'les-208', title: '08 - حقيبة الإسعافات والاختبار النهائي', duration: '25 دقيقة', order: 8, summary: 'مكونات الحقيبة الميدانية واختبار المعارف.' },
    ],
  },
  {
    id: 'course-003',
    title: 'إدارة المشاريع والمبادرات المجتمعية',
    subtitle: 'من الفكرة إلى التنفيذ والتقييم: خطوات عملية لبناء مشاريع جمعوية ناجحة.',
    description:
      'تعلم كيف تبني خطة عمل واضحة لمبادرتك، تحدد الميزانية والموارد، تدير المخاطر، وتقنع الشركاء والجهات المانحة بدعم مشروعك.',
    category: 'إدارة المشاريع',
    rating: 4.7,
    learnersCount: 890,
    duration: '3 ساعات و 15 دقيقة',
    lessonsCount: 5,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=800',
    instructor: {
      name: 'أ. طارق بلحاج',
      role: 'مستشار مشاريع تنموية لدى منظمات شبابية',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    },
    outcomes: [
      'صياغة وثيقة مشروع احترافية وفق نموذج العمل الجمعوي',
      'تحديد الأهداف الذكية (SMART) والمؤشرات الدقيقة',
      'إعداد ميزانية واقعية وجدول زمني محكم',
      'إدارة المخاطر وحل العقبات الطارئة',
    ],
    certificatePriceDzd: 1500,
    certificatePricePoints: 100,
    featured: true,
    lessons: [
      { id: 'les-301', title: '01 - تحديد الاحتياج المجتمعي وتوليد الأفكار', duration: '35 دقيقة', order: 1, summary: 'دراسة المشكلة المحلية واختيار الحلول القابلة للتطبيق.' },
      { id: 'les-302', title: '02 - صياغة الأهداف ومؤشرات النجاح', duration: '40 دقيقة', order: 2, summary: 'كيف تجعل أهداف مبادرتك قابلة للقياس والتحقيق.' },
      { id: 'les-303', title: '03 - إدارة الموارد البشرية والمالية', duration: '45 دقيقة', order: 3, summary: 'توزيع المهام بين المتطوعين وضبط التكاليف بدقة.' },
      { id: 'les-304', title: '04 - التسويق للمبادرة واستقطاب الدعم', duration: '35 دقيقة', order: 4, summary: 'كيف تقدم مشروعك للداعمين والمؤسسات الراعية.' },
      { id: 'les-305', title: '05 - المتابعة والتقييم وإعداد التقرير الختامي', duration: '40 دقيقة', order: 5, summary: 'توثيق العوائد واستخلاص الدروس للمشاريع اللاحقة.' },
    ],
  },
  {
    id: 'course-004',
    title: 'القيادة والتواصل الفعال في العمل الجمعوي',
    subtitle: 'طور شخصيتك القيادية والهم فريقك لإحداث أثر جماعي مضاعف.',
    description:
      'اكتشف أسرار القيادة التحفيزية، التحدث أمام الجمهور، الإقناع، وإدارة اجتماعات الجمعية بإنتاجية وروح إيجابية عالية.',
    category: 'القيادة',
    rating: 4.8,
    learnersCount: 1560,
    duration: 'ساعتان كاملتان',
    lessonsCount: 4,
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800',
    instructor: {
      name: 'أ. سارة بوعكاز',
      role: 'مدربة في القيادة الشابة والتنمية الذاتية',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    },
    outcomes: [
      'معرفة أنماط القيادة واختيار الأنسب لفرق التطوع',
      'فنون الإلقاء والتحدث بثقة أمام الجماهير',
      'تحفيز المتطوعين وبناء ولاء مستمر للقضية',
      'إدارة الاجتماعات وحسم القرارات الجماعية',
    ],
    certificatePriceDzd: 1500,
    certificatePricePoints: 100,
    lessons: [
      { id: 'les-401', title: '01 - من المتطوع الفرد إلى القائد الملهم', duration: '30 دقيقة', order: 1, summary: 'السمات العشر للقائد الجمعوي الناجح.' },
      { id: 'les-402', title: '02 - فن الاستماع والذكاء العاطفي مع الفريق', duration: '30 دقيقة', order: 2, summary: 'كيف تبني جسور الثقة المتبادلة بين المتطوعين.' },
      { id: 'les-403', title: '03 - التواصل المقنع وفن الخطابة المجتمعية', duration: '30 دقيقة', order: 3, summary: 'صياغة رسائل ملهمة تؤثر في الجمهور والمستفيدين.' },
      { id: 'les-404', title: '04 - إدارة الأزمات والضغوط القيادية', duration: '30 دقيقة', order: 4, summary: 'الحفاظ على تماسك الفريق في الأوقات الصعبة.' },
    ],
  },
  {
    id: 'course-005',
    title: 'التسويق الرقمي وصناعة المحتوى للمنظمات غير الربحية',
    subtitle: 'استخدم وسائل التواصل الاجتماعي لزيادة الوعي وجلب الدعم والمتطوعين.',
    description:
      'تعلم كيف تسرد قصص نجاح مبادراتك، تصمم محتوى بصري جذاب بالهاتف، وتطلق حملات رقمية تحقق تفاعلاً كبيراً.',
    category: 'التكنولوجيا',
    rating: 4.6,
    learnersCount: 740,
    duration: 'ساعتان و 45 دقيقة',
    lessonsCount: 4,
    image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=800',
    instructor: {
      name: 'م. وليد عماري',
      role: 'متخصص في استراتيجيات التسويق الرقمي وصناعة المحتوى',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    },
    outcomes: [
      'بناء هوية رقمية متناسقة للجمعية',
      'كتابة محتوى إنساني مؤثر (Storytelling)',
      'تصميم بوستات وفيديوهات قصيرة بأدوات مجانية',
      'إدارة حملات التوعية واستقطاب التبرعات رقمياً',
    ],
    certificatePriceDzd: 1500,
    certificatePricePoints: 100,
    lessons: [
      { id: 'les-501', title: '01 - فهم المنصات والجمهور المستهدف', duration: '40 دقيقة', order: 1, summary: 'الفروق بين فيسبوك، إنستغرام، وتيك توك في العمل الخيري.' },
      { id: 'les-502', title: '02 - قوة السرد القصصي (Storytelling)', duration: '45 دقيقة', order: 2, summary: 'كيف تحول أرقام نشاطك الميداني إلى قصص إنسانية مؤثرة.' },
      { id: 'les-503', title: '03 - أدوات التصميم البصري والفيديو السريع', duration: '40 دقيقة', order: 3, summary: 'استخدام كانفا وتطبيقات المونتاج بالهاتف.' },
      { id: 'les-504', title: '04 - إدارة حملات التبرع وجذب المتطوعين', duration: '40 دقيقة', order: 4, summary: 'إطلاق نداءات استغاثة وحملات تطوعية رقمية ناجحة.' },
    ],
  },
  {
    id: 'course-006',
    title: 'التطوع البيئي وتدوير النفايات المنزلية',
    subtitle: 'دليل عملي لتنظيم حملات بيئية مستدامة ونشر ثقافة الفرز في الأحياء.',
    description:
      'تعرف على الأثر المناخي، طرق فرز وتدوير النفايات البلاستيكية والعضوية، وكيفية إطلاق نوادٍ بيئية في المدارس والأحياء.',
    category: 'البيئة',
    rating: 4.9,
    learnersCount: 920,
    duration: 'ساعة و 45 دقيقة',
    lessonsCount: 3,
    image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80&w=800',
    instructor: {
      name: 'أ. نادية مزيان',
      role: 'ناشطة بيئية وباحثة في الاقتصاد الدائري',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    },
    outcomes: [
      'فهم دورة حياة النفايات وأثرها على الطبيعة',
      'خطوات إنشاء نادي بيئي حيي أو مدرسي',
      'تطبيق الفرز الانتقائي في المنزل والجمعية',
    ],
    certificatePriceDzd: 1500,
    certificatePricePoints: 100,
    lessons: [
      { id: 'les-601', title: '01 - النفايات والمناخ: التحدي البيئي في الجزائر', duration: '35 دقيقة', order: 1, summary: 'أرقام وحقائق عن الاستهلاك والنفايات في المدن.' },
      { id: 'les-602', title: '02 - الفرز من المصدر وإعادة التدوير العملي', duration: '35 دقيقة', order: 2, summary: 'كيف تصنف البلاستيك، الورق، والنفايات العضوية بسهولة.' },
      { id: 'les-603', title: '03 - إطلاق مبادرات بيئية في حيك أو مدرستك', duration: '35 دقيقة', order: 3, summary: 'خطوات تنظيم حملة تنظيف وتشجير تدوم طويلاً.' },
    ],
  },
];

// Donation Campaigns
export const initialDonations: Donation[] = [
  {
    id: 'don-001',
    title: 'دعم الأطفال المعوزين وتوفير الحقائب المدرسية',
    description: 'مساعدة 100 تلميذ من العائلات ذات الدخل المحدود وتزويدهم بالحقائب والأدوات المدرسية الكاملة.',
    detailedDescription:
      'مع الدخول المدرسي الجديد، تجد الكثير من العائلات صعوبة بالغة في توفير المستلزمات والكتب لأبنائها. تهدف هذه الحملة إلى كفالة 100 حقيبة مدرسية متكاملة تضمن عودة كريمة ومبهجة لأطفالنا في مقاعد الدراسة.',
    category: 'التعليم',
    targetAmount: 100000,
    raisedAmount: 72000,
    donorsCount: 148,
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800',
    organizationName: 'جمعية الأمل لرعاية الشباب والبيئة',
    daysLeft: 12,
    urgent: true,
    featured: true,
    updates: [
      { date: '2026-09-15', title: 'اقتناء الدفعة الأولى من الأدوات', content: 'تم شراء 50 محفظة مجهزة بدفاتر وأقلام من التبرعات الأولية.' },
      { date: '2026-09-18', title: 'تجهيز قائمة المستفيدين في بجاية', content: 'تم حصر العائلات الأكثر احتياجاً بالتنسيق مع مديري المدارس الابتدائية.' },
    ],
  },
  {
    id: 'don-002',
    title: 'حملة الدفء والشتاء للقرى المعزولة في الجلفة',
    description: 'توفير أغطية صوفية ومدافئ وملابس شتوية ثقيلة للأسر في المناطق الجبلية والباردة.',
    detailedDescription:
      'تشهد ولاية الجلفة ومناطق الهضاب العليا انخفاضاً حاداً في درجات الحرارة وتساقطاً للثلوج. نسعى لجمع التبرعات لشراء 200 غطاء صوفي ثقيل ومساعدات غذائية مقاومة للبرد القارس.',
    category: 'التضامن',
    targetAmount: 250000,
    raisedAmount: 185000,
    donorsCount: 230,
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=800',
    organizationName: 'جمعية صناع الأثر وهران',
    daysLeft: 25,
    urgent: true,
    featured: true,
    updates: [
      { date: '2026-09-10', title: 'انطلاق الحملة الإنسانية', content: 'بدء استقبال المساهمات وتحديد القرى المستهدفة في دائرة عين وسارة.' },
    ],
  },
  {
    id: 'don-003',
    title: 'تجهيز قاعات الحوسبة في المدارس الريفية',
    description: 'شراء وتثبيت حواسيب مجددة لفتح آفاق التكنولوجيا أمام 500 تلميذ في البليدة.',
    detailedDescription:
      'تمكين تلاميذ المناطق الريفية من التعلم الرقمي واستخدام الحاسوب في بحوثهم ودروسهم عبر تزويد 3 مدارس ابتدائية بمخابر حاسوب مصغرة ومتصلة بالإنترنت التعليمي.',
    category: 'التكنولوجيا',
    targetAmount: 400000,
    raisedAmount: 310000,
    donorsCount: 315,
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800',
    organizationName: 'نادي تكنولوجيا المستقبل للشباب',
    daysLeft: 18,
    urgent: false,
    featured: true,
  },
  {
    id: 'don-004',
    title: 'توفير المياه الصالحة للشرب لواحات أدرار',
    description: 'صيانة قنوات الفقارات التقليدية وحفر بئر ارتوازي بالطاقة الشمسية لسقي النخيل والشرب.',
    detailedDescription:
      'حماية الواحات الجزائرية العريقة من الجفاف ودعم العائلات الفلاحية بتوفير مضخات مياه شمسية وصيانة شبكات السقي التقليدية في أدرار وتيميمون.',
    category: 'البيئة',
    targetAmount: 300000,
    raisedAmount: 145000,
    donorsCount: 190,
    image: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=800',
    organizationName: 'الهلال الأحمر الجزائري - لجنة البليدة',
    daysLeft: 40,
    urgent: false,
    featured: false,
  },
];

// Achievements / Badges
export const initialAchievements: Achievement[] = [
  {
    id: 'first_volunteer',
    title: 'أول خطوة تطوعية 🏅',
    description: 'أكملت أول نشاط تطوعي موثق على المنصة بنجاح.',
    icon: '🏅',
    unlocked: true,
    unlockedAt: '2026-03-12',
  },
  {
    id: 'environment_volunteer',
    title: 'صديق البيئة 🌱',
    description: 'شاركت في 3 مبادرات بيئية لحماية الطبيعة والتشجير.',
    icon: '🌱',
    unlocked: true,
    unlockedAt: '2026-05-20',
  },
  {
    id: '10_volunteering',
    title: 'بطل العطاء (10 تطوعات) 🤝',
    description: 'أكملت 10 مشاركات تطوعية وساهمت في تنمية مجتمعك.',
    icon: '🤝',
    unlocked: true,
    unlockedAt: '2026-08-14',
  },
  {
    id: 'first_course',
    title: 'متعلم نشط 🎓',
    description: 'أكملت دورة تدريبية وحصلت على شهادة معتمدة.',
    icon: '🎓',
    unlocked: true,
    unlockedAt: '2026-09-02',
  },
  {
    id: '500_points',
    title: 'نادي الـ 500 نقطة 🏆',
    description: 'جمعت 500 نقطة تطوعية من خلال العطاء المستمر.',
    icon: '🏆',
    unlocked: false,
    progress: 350,
    maxProgress: 500,
  },
  {
    id: 'community_helper',
    title: 'متطوع متميز ⭐',
    description: 'تجاوزت 40 ساعة تطوع ميدانية مع تقييم ممتاز.',
    icon: '⭐',
    unlocked: true,
    unlockedAt: '2026-09-10',
  },
  {
    id: 'learning_champion',
    title: 'سفير المعرفة 👑',
    description: 'أتممت 5 دورات تدريبية مختلفة على المنصة.',
    icon: '👑',
    unlocked: false,
    progress: 1,
    maxProgress: 5,
  },
];

// Point transactions history for mock user
export const initialPointTransactions: PointTransaction[] = [
  {
    id: 'tx-001',
    title: 'تنظيف الشواطئ في بجاية',
    points: 50,
    type: 'credit',
    date: '2026-09-18',
    category: 'تطوع ميداني',
  },
  {
    id: 'tx-002',
    title: 'توزيع مساعدات قفف رمضان',
    points: 30,
    type: 'credit',
    date: '2026-08-25',
    category: 'تطوع ميداني',
  },
  {
    id: 'tx-003',
    title: 'تنظيم وتأطير الفعالية الثقافية للشباب',
    points: 70,
    type: 'credit',
    date: '2026-08-10',
    category: 'تنظيم فعاليات',
  },
  {
    id: 'tx-004',
    title: 'الحصول على شهادة أساسيات العمل التطوعي',
    points: 100,
    type: 'debit',
    date: '2026-07-28',
    category: 'شراء شهادة',
  },
  {
    id: 'tx-005',
    title: 'حملة تشجير غابات البليدة',
    points: 70,
    type: 'credit',
    date: '2026-06-15',
    category: 'تطوع ميداني',
  },
];

// Leaderboard Top Volunteers in Algeria
export const initialLeaderboard: LeaderboardUser[] = [
  {
    rank: 1,
    id: 'lead-001',
    name: 'أحمد بن عبد الله',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    wilaya: 'الجزائر',
    points: 1250,
    volunteerCount: 28,
    level: 'سفير تطوع',
  },
  {
    rank: 2,
    id: 'lead-002',
    name: 'سارة مرابط',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    wilaya: 'وهران',
    points: 1120,
    volunteerCount: 24,
    level: 'سفير تطوع',
  },
  {
    rank: 3,
    id: 'lead-003',
    name: 'أمين قادري',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    wilaya: 'قسنطينة',
    points: 980,
    volunteerCount: 19,
    level: 'متطوع متميز',
  },
  {
    rank: 4,
    id: 'lead-004',
    name: 'ياسمين بلحاج',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    wilaya: 'عنابة',
    points: 840,
    volunteerCount: 17,
    level: 'متطوع متميز',
  },
  {
    rank: 5,
    id: 'lead-005',
    name: 'بلال سعيدي',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    wilaya: 'سطيف',
    points: 710,
    volunteerCount: 15,
    level: 'متطوع متميز',
  },
  {
    rank: 6,
    id: 'lead-006',
    name: 'فاطمة بوزيد',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    wilaya: 'تلمسان',
    points: 620,
    volunteerCount: 14,
    level: 'متطوع متميز',
  },
  {
    rank: 7,
    id: 'user-001',
    name: 'محمد أحمد (أنت)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    wilaya: 'الجزائر',
    points: 350,
    volunteerCount: 12,
    level: 'متطوع نشط',
  },
];

// Initial Applications for the Volunteer
export const initialApplications: Application[] = [
  {
    id: 'app-001',
    opportunityId: 'opp-001',
    opportunityTitle: 'تنظيف الشواطئ وحماية الساحل في بجاية',
    opportunityImage: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&q=80&w=800',
    organizationName: 'جمعية الأمل لرعاية الشباب والبيئة',
    organizationLogo: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=200',
    volunteerId: 'user-001',
    volunteerName: 'محمد أحمد',
    volunteerEmail: 'mohamed@example.com',
    volunteerPhone: '0550 12 34 56',
    volunteerWilaya: 'الجزائر',
    appliedDate: '2026-09-18',
    status: 'completed',
    pointsAwarded: 50,
    rating: 5,
    note: 'متطوع منضبط وملتزم، أظهر تفانياً كبيراً في تنظيف الشاطئ.',
  },
  {
    id: 'app-002',
    opportunityId: 'opp-002',
    opportunityTitle: 'حملة تشجير غابات الأطلس البليدي',
    opportunityImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    organizationName: 'الهلال الأحمر الجزائري - لجنة البليدة',
    organizationLogo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=200',
    volunteerId: 'user-001',
    volunteerName: 'محمد أحمد',
    volunteerEmail: 'mohamed@example.com',
    volunteerPhone: '0550 12 34 56',
    volunteerWilaya: 'الجزائر',
    appliedDate: '2026-09-15',
    status: 'accepted',
  },
  {
    id: 'app-003',
    opportunityId: 'opp-003',
    opportunityTitle: 'دروس دعم وتقوية مجانية لتلاميذ الابتدائي',
    opportunityImage: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&q=80&w=800',
    organizationName: 'جمعية الأمل لرعاية الشباب والبيئة',
    organizationLogo: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&q=80&w=200',
    volunteerId: 'user-001',
    volunteerName: 'محمد أحمد',
    volunteerEmail: 'mohamed@example.com',
    volunteerPhone: '0550 12 34 56',
    volunteerWilaya: 'الجزائر',
    appliedDate: '2026-09-19',
    status: 'pending',
  },
];

// Initial Earned Certificates
export const initialCertificates: Certificate[] = [
  {
    id: 'cert-001',
    certificateCode: 'TW-2026-00125',
    courseId: 'course-001',
    courseTitle: 'أساسيات العمل التطوعي وصناعة الأثر الإيجابي',
    recipientName: 'محمد أحمد',
    issueDate: '20 سبتمبر 2026',
    paymentMethod: 'points',
    pricePaid: '100 نقطة تطوع',
    verified: true,
  },
];

// Initial Notifications
export const initialNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'تم قبول طلبك 🎉',
    description: 'تم قبولك للمشاركة في: حملة تشجير غابات الأطلس البليدي.',
    time: 'منذ ساعتين',
    read: false,
    type: 'application',
    link: '/profile/applications',
  },
  {
    id: 'notif-002',
    title: '+50 نقطة تطوع جديدة 🏆',
    description: 'تم تأكيد مشاركتك في تنظيف الشواطئ ببجاية وإيداع 50 نقطة في رصيدك.',
    time: 'منذ يوم',
    read: false,
    type: 'points',
    link: '/profile/points',
  },
  {
    id: 'notif-003',
    title: 'شهادة جديدة في ملفك 📜',
    description: 'تهانينا! أتممت بنجاح دورة أساسيات العمل التطوعي.',
    time: 'منذ 3 أيام',
    read: true,
    type: 'certificate',
    link: '/profile/certificates',
  },
  {
    id: 'notif-004',
    title: 'فرصة تطوعية جديدة في ولايتك 🌱',
    description: 'فرصة جديدة: دروس دعم وتقوية في الجزائر الوسطى.',
    time: 'منذ 4 أيام',
    read: true,
    type: 'opportunity',
    link: '/opportunities/opp-003',
  },
];
